### ISSUE TITLE
Support for media-query scoped properties

### ISSUE THREAD

**Issue by pgregorova** [connectivedx/fuzzy-chainsaw#337]
it would be nice to be able to separate logic from design by using dynamic variables, where we set the variables and change its value as desired within breakpoint within `:root`.

## Expected Behavior
```CSS
:root { --fontSize: 2rem; }

@media (min-width: 64rem) {
   :root { --font-size: 3rem; }
}
```

## Current Behavior
Currently it's impossible change value for a variable in `:root`, which is wrapped within media query. It simply throws errors and doesn't compile. Similar issue has been also reported in [PostCSS's issue ticket related to custom properties](https://github.com/postcss/postcss-custom-properties/issues/9), where you can see more examples. 

## Steps to Reproduce (for bugs)
You can use [my codepen for responsive table](https://codepen.io/pgregorova/pen/QqQNwg), where I was testing it just using PostCSS, no CSSNext and it works like a charm.
